### ISSUE TITLE
AddOn Dresser attempted to call a forbidden function (JoinBattlefield()) from a tainted execution path.

### ISSUE THREAD

**Issue by fjdiazt** [Vladinator89/wow-addon-dresser#1]
Date: 2017-10-27 17:03:14
ID: 1
Error occured in: AddOn: Dresser
Count: 9
Message: Error: AddOn Dresser attempted to call a forbidden function (JoinBattlefield()) from a tainted execution path.
Debug:
   [C]: JoinBattlefield()
   Blizzard_PVPUI\Blizzard_PVPUI.lua:611: HonorFrame_Queue()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  Ace3, v
  AdiBags, vv1.9.8
  Altoholic, vr183
  Atlas, vv1.43.03
  AtlasBattlegrounds, vv1.43.00
  AtlasBurningCrusade, vv1.43.00
  AtlasCataclysm, vv1.43.00
  AtlasClassicWoW, vv1.43.00
  AtlasClassOrderHalls, vv1.43.00
  AtlasDungeonLocs, vv1.43.00
  AtlasLegion, vv1.43.03
  AtlasMistsofPandaria, vv1.43.00
  AtlasOutdoorRaids, vv1.43.00
  AtlasScenarios, vv1.43.00
  AtlasTransportation, vv1.43.00
  AtlasWarlordsofDraenor, vv1.43.00
  AtlasWorldEvents, vv3.23
  AtlasWrathoftheLichKing, vv1.43.00
  AtlasLoot, vv8.07.01
  AtlasLootBurningCrusade, vv8.07.01
  AtlasLootCataclysm, vv8.07.01
  AtlasLootClassic, vv8.07.01
  AtlasLootLegion, vv8.07.01
  AtlasLootMistsofPandaria, vv8.07.01
  AtlasLootWarlordsofDraenor, vv8.07.01
  AtlasLootWrathoftheLichKing, vv8.07.01
  Bartender4, v4.7.10
  Coordinates, v1.23
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  Dresser, v7.2.0.170329
  GoGoMount, v7.1.1
  GoGoMountExtraMounts, v2.0
  GoGoMountManager, v1.0
  Grail, v091
  GrailAchievements, v011
  GrailReputations, v007
  Immersion, v0.5.1
  InstancePortals, v8
  OmniCC, v7.3
  Quester, v7.3.0.0
  QuestLevelPatch, vv1.23
  SlideBar, v7.3.1 (<%codename%>)
  TransmogTokens, v1.4.8
  Wholly, v064
  WorldQuestsList, v48
  WorldQuestTab, v7.3.02e
  BlizRuntimeLib_enUS v7.3.2.70300 <none>
  (ck=6b0)

**Comment by Vladinator** [comment]
I am avoiding taint issues like this by simply using a custom dropdown library. This is now hopefully fixed with the october commit.
