### ISSUE TITLE
  Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], 

### ISSUE THREAD

**Issue by fjdiazt** [Vladinator89/wow-addon-dresser#2]
Date: 2017-10-27 19:34:55
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Dresser\core.lua line 350:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   Dresser\core.lua:350:
      Dresser\core.lua:336
Locals:
(*temporary) = "gsTitleOptionOK"

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  Ace3, v
  AdiBags, vv1.9.8
  Altoholic, vr183
  Atlas, vv1.43.03
  AtlasBattlegrounds, vv1.43.00
  AtlasBurningCrusade, vv1.43.00
  AtlasCataclysm, vv1.43.00
  AtlasClassicWoW, vv1.43.00
  AtlasClassOrderHalls, vv1.43.00
  AtlasDungeonLocs, vv1.43.00
  AtlasLegion, vv1.43.03
  AtlasMistsofPandaria, vv1.43.00
  AtlasOutdoorRaids, vv1.43.00
  AtlasScenarios, vv1.43.00
  AtlasTransportation, vv1.43.00
  AtlasWarlordsofDraenor, vv1.43.00
  AtlasWorldEvents, vv3.23
  AtlasWrathoftheLichKing, vv1.43.00
  AtlasLoot, vv8.07.01
  AtlasLootBurningCrusade, vv8.07.01
  AtlasLootCataclysm, vv8.07.01
  AtlasLootClassic, vv8.07.01
  AtlasLootLegion, vv8.07.01
  AtlasLootMistsofPandaria, vv8.07.01
  AtlasLootWarlordsofDraenor, vv8.07.01
  AtlasLootWrathoftheLichKing, vv8.07.01
  Babylonian, v5.1.DEV.332(/embedded)
  Bartender4, v4.7.10
  Configator, v5.1.DEV.431(/embedded)
  Coordinates, v1.23
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  Dresser, v7.2.0.170329
  Gatherer, v7.3.1
  GoGoMount, v7.1.1
  GoGoMountExtraMounts, v2.0
  GoGoMountManager, v1.0
  Grail, v091
  GrailAchievements, v011
  GrailQuestsenUS, v24920
  GrailReputations, v007
  Immersion, v0.5.1
  InstancePortals, v8
  OmniCC, v7.3
  PetTracker, v7.3.0
  PetTrackerBreeds, v7.3.0
  PetTrackerConfig, v7.3.0
  PetTrackerJournal, v7.3.0
  PetTrackerSwitcher, v7.3.0
  PetTrackerUpgrades, v7.3.0
  Quester, v7.3.0.0
  QuestLevelPatch, vv1.23
  SlideBar, v7.3.1 (<%codename%>)
  TransmogTokens, v1.4.8
  Wholly, v064
  WorldQuestsList, v48
  WorldQuestTab, v7.3.02e
  BlizRuntimeLib_enUS v7.3.2.70300 <none>
  (ck=7ca)

**Comment by Vladinator** [comment]
This was indeed a issue with many addons playing sounds on button clicks and similar. It was fixed a while ago, but finally closing the ticket related to the issue.
